[build]
  publish = "dist/"
  command = "yarn generate"

[template.environment]
  BASE_URL="https://saulo.codes"
  GOOGLE_ANALYTICS_ID=
  NOTION_TABLE_ID="cd240ed3c58d49608077d21352ada309"
  NOTION_ABOUT_PAGE_ID="Hi-there-cc487b79fd7f40ba8e14b1f3ec4a82c7"
  GITHUB_USERNAME="sauloco"
  DEV_LOGO="saulo.codes"
  DEV_NAME="Saulo Vargas"
  DEV_DESCRIPTION="I guide startups from ✏ design to 🚀 launch. Building robust yet modern JavaScript & TypeScript based mobile and web experiences. Founder @ RusticIT & Full Stack Developer @ Synphonyte"
  DEV_ROLE="Senior Full Stack Developer"
  DEV_GITHUB_LINK="https://github.com/sauloco"
  DEV_TWITTER_LINK="https://twitter.com/sauloco"
  DEV_LINKEDIN_LINK="https://www.linkedin.com/in/saulovargas"
